title: Nicole Baltodano
logo: /images/portfolio.png
description: >
  Data Scientist passionate about Materials Science, with expertise in Data Science, AI, and Metallurgical Engineering.

education:
  - degree: M.S., Data Science
    institution: University of Wisconsin – Milwaukee
    period: 2024 – 2025
  - degree: Bootcamp, Data Science and AI
    institution: Le Wagon, Montreal
    period: 2023
  - degree: M.S., Metallurgical Engineering
    institution: CINVESTAV, Mexico
    period: 2021 – 2023
  - degree: B.Sc., Chemical Engineering
    institution: UNI, Nicaragua
    period: 2014 – 2021

contact:
  email: nicolbaltodano@hotmail.com
  linkedin: https://www.linkedin.com/in/nicole-baltodano-460941191/
  location: Milwaukee, Wisconsin

theme: jekyll-theme-minimal
