title: Nicole Baltodano
logo: /images/portfolio.png
description: Data Scientist passionate about Materials Science
education:
  - M.S., Data Science - University of Wisconsin – Milwaukee (2024 – 2025)
  - Bootcamp, Data Science and AI - Le Wagon, Montreal (2023)
  - M.S., Metallurgical Engineering - CINVESTAV, Mexico (2021-2023)
  - BSc., Chemical Engineering - UNI, Nicaragua (2014 – 2021)

contact:
  email: nicolbaltodano@hotmail.com
  linkedin: https://www.linkedin.com/in/nicole-baltodano-460941191/
  location: Milwaukee, Wisconsin
theme: jekyll-theme-minimal
